// API: Get Settings
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAIL = "GET_SETTINGS_FAIL";
export const GET_SETTINGS_STARTED = "GET_SETTINGS_STARTED";

// API: Get Models
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_FAILED = "GET_MODELS_FAILED";
export const GET_MODELS_STARTED = "GET_MODELS_STARTED";

// API: Get Model
export const GET_MODEL_SUCCESS = "GET_MODEL_SUCCESS";
export const GET_MODEL_FAILED = "GET_MODEL_FAILED";
export const GET_MODEL_STARTED = "GET_MODEL_STARTED";

// API: Get Ads
export const GET_ADS_SUCCESS = "GET_ADS_SUCCESS";
export const GET_ADS_FAILED = "GET_ADS_FAILED";
export const GET_ADS_STARTED = "GET_ADS_STARTED";

// API: Get Ad
export const GET_AD_SUCCESS = "GET_AD_SUCCESS";
export const GET_AD_FAILED = "GET_AD_FAILED";
export const GET_AD_STARTED = "GET_AD_STARTED";

// API: POST Sessions
export const REQUEST_CODE_STARTED = "REQUEST_CODE_STARTED";
export const REQUEST_CODE_SUCCESS = "REQUEST_CODE_SUCCESS";
export const REQUEST_CODE_FAILED = "REQUEST_CODE_FAILED";

// API: Put Sessions
export const SIGN_IN_STARTED = "SIGN_IN_STARTED";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

// API: Delete Sessions
export const SIGN_OUT_STARTED = "SIGN_OUT_STARTED";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILED = "SIGN_OUT_FAILED";

// API: Put Contacts
export const UPDATE_CONTACTS_STARTED = "UPDATE_CONTACTS_STARTED";
export const UPDATE_CONTACTS_SUCCESS = "UPDATE_CONTACTS_SUCCESS";
export const UPDATE_CONTACTS_FAILED = "UPDATE_CONTACTS_FAILED";

// API: Get Contacts
export const GET_CONTACTS_STARTED = "GET_CONTACTS_STARTED";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED";

// API: Post Ads:AskFriend
export const ASK_FRIEND_STARTED = "ASK_FRIEND_STARTED";
export const ASK_FRIEND_SUCCESS = "ASK_FRIEND_SUCCESS";
export const ASK_FRIEND_FAILED = "ASK_FRIEND_FAILED";

// Autocomplete
export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";
export const MAYBE_UPDATE_SUGGESTIONS = "MAYBE_UPDATE_SUGGESTIONS";
export const LOAD_SUGGESTIONS_BEGIN = "LOAD_SUGGESTIONS_BEGIN";
export const LOAD_SUGGESTIONS_FAILED = "LOAD_SUGGESTIONS_FAILED";

// Misc
export const SEARCH_FILTER_CHANGED = "SEARCH_FILTER_CHANGED";
export const ADS_FILTERED = "ADS_FILTERED";
export const SET_ADS_SOURCE = "SET_ADS_SOURCE";
export const SET_ERROR = "SET_ERROR";

// Modals
export const SHOW_SESSION_MODAL = "SHOW_SESSION_MODAL";
export const HIDE_SESSION_MODAL = "HIDE_SESSION_MODAL";
