// API: Get Settings
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAIL = "GET_SETTINGS_FAIL";
export const GET_SETTINGS_STARTED = "GET_SETTINGS_STARTED";

// API: Get Models
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_FAILED = "GET_MODELS_FAILED";
export const GET_MODELS_STARTED = "GET_MODELS_STARTED";

// API: Get Model
export const GET_MODEL_SUCCESS = "GET_MODEL_SUCCESS";
export const GET_MODEL_FAILED = "GET_MODEL_FAILED";
export const GET_MODEL_STARTED = "GET_MODEL_STARTED";

// API: Get Ads
export const GET_ADS_SUCCESS = "GET_ADS_SUCCESS";
export const GET_ADS_FAILED = "GET_ADS_FAILED";
export const GET_ADS_STARTED = "GET_ADS_STARTED";

// API: Get Ad
export const GET_AD_SUCCESS = "GET_AD_SUCCESS";
export const GET_AD_FAILED = "GET_AD_FAILED";
export const GET_AD_STARTED = "GET_AD_STARTED";

// Autocomplete
export const UPDATE_INPUT_VALUE = "UPDATE_INPUT_VALUE";
export const CLEAR_SUGGESTIONS = "CLEAR_SUGGESTIONS";
export const MAYBE_UPDATE_SUGGESTIONS = "MAYBE_UPDATE_SUGGESTIONS";
export const LOAD_SUGGESTIONS_BEGIN = "LOAD_SUGGESTIONS_BEGIN";
export const LOAD_SUGGESTIONS_FAILED = "LOAD_SUGGESTIONS_FAILED";

// Misc
export const SEARCH_FILTER_CHANGED = "SEARCH_FILTER_CHANGED";
export const ADS_FILTERED = "ADS_FILTERED";
export const SET_ADS_SOURCE = "SET_ADS_SOURCE";
export const SET_ERROR = "SET_ERROR";
